/* Question bank — Managing Data (9MD) and Digital Communication (9DC) */
window.BANK = window.BANK || {};
Object.assign(window.BANK, {

"9MD.01": [
  ["What is a computer model?", "A simplified representation of a real-life system using data and rules", ["A plastic toy computer", "A new type of laptop", "A list of passwords"]],
  ["Which is an example of a computer model?", "A weather forecast simulation", ["A word-processed letter", "A photo of a beach", "An email"]],
  ["Why might engineers test a bridge design with a model first?", "It is safer and cheaper than building the real thing first", ["Models are always 100% accurate", "Real bridges can't be tested", "It is more fun"]],
  ["What is a 'what if?' question in modelling?", "Changing a value to see what would happen", ["Asking the teacher for help", "A question with no answer", "Deleting the model"]],
  ["Which is a LIMITATION of models?", "They are simplified and may leave out important factors", ["They are always correct", "They can't use numbers", "They are always expensive"]],
  ["'Garbage in, garbage out' means…", "if the input data is wrong, the results will be wrong", ["models create rubbish", "you must delete old files", "printers waste paper"]],
  ["How can you check if a model is accurate?", "Compare its results to what really happens", ["Make it more colourful", "Add more pages", "Use a bigger font"]],
  ["A flight simulator is used to train pilots. What is the main benefit?", "Pilots can practise dangerous situations safely", ["It makes real planes faster", "It is exactly the same as flying", "It needs no computer"]],
  ["A traffic model ignores road works. What could happen?", "Its predictions could be wrong", ["It becomes more accurate", "It runs faster and is perfect", "Nothing at all"]],
  ["Which question helps EVALUATE a model?", "Is the data accurate and up to date?", ["What font does it use?", "How heavy is the computer?", "Who typed it?"]],
  ["Why do scientists use models to predict the spread of a disease?", "To test different plans (like vaccines) without risking lives", ["To spread the disease faster", "Because real data is illegal", "To avoid collecting any data"]],
  ["Which is an advantage of a computer model?", "It can simulate years of events in seconds", ["It never needs data", "It is never wrong", "It replaces all real testing"]]
],

"9MD.02": [
  ["Which function finds the largest value in a range?", "MAX", ["MIN", "COUNT", "IF"], {t: ["max"]}],
  ["Which function finds the smallest value in a range?", "MIN", ["MAX", "COUNT", "SUM"], {t: ["min"]}],
  ["Which function counts how many cells contain numbers?", "COUNT", ["MAX", "SUM", "IF"], {t: ["count"]}],
  ["Which function checks a condition and gives one of two results?", "IF", ["MIN", "COUNT", "MAX"], {t: ["if"]}],
  ["What does every spreadsheet formula start with?", "=", ["+", "#", "?"], {t: ["="]}],
  ["Which formula shows 'Pass' if B2 is 50 or more, otherwise 'Fail'?", "=IF(B2>=50,\"Pass\",\"Fail\")", ["=IF(B2>50,Pass,Fail)", "=IF(\"Pass\",B2>=50,\"Fail\")", "=MAX(B2,\"Pass\")"]],
  ["Cells A1:A5 contain 12, 7, \"abc\", 20 and an empty cell. What does =COUNT(A1:A5) give?", "3", ["5", "4", "39"], {t: true, e: "COUNT only counts cells with numbers — not text or empty cells."}],
  ["What does <> mean in a spreadsheet condition?", "Not equal to", ["Less than or equal", "Greater than", "Equal to"]],
  ["Which formula finds the highest score in C2 to C30?", "=MAX(C2:C30)", ["=MAX(C2+C30)", "=HIGH(C2:C30)", "MAX=C2:C30"]],
  ["What does C2:C30 mean?", "A range — all the cells from C2 to C30", ["Only cells C2 and C30", "C2 divided by C30", "Column C, row 2 multiplied by 30"]],
  ["Why must text inside an IF formula be in quotation marks?", "So the spreadsheet knows it is text, not a cell or function name", ["To make it bold", "To make it a number", "Quotation marks are never needed"]],
  ["=IF(A1>100,\"High\",\"Low\") — what is shown if A1 = 100?", "Low", ["High", "100", "An error"], {t: ["low"]}]
],

"9MD.03": [
  ["What is the main advantage of using formulas in a spreadsheet model?", "When an input changes, the results recalculate automatically", ["The spreadsheet looks colourful", "Formulas never need checking", "They make the file smaller"]],
  ["In a trip budget model, B1 = students and B2 = cost each. Which formula gives the total cost?", "=B1*B2", ["=B1+B2", "B1*B2", "=SUM(B1)"]],
  ["What should you do FIRST when creating a spreadsheet model?", "Decide what the model needs to show (inputs, rules and outputs)", ["Choose a font", "Print it", "Add a chart"]],
  ["Which is an INPUT in a pocket-money savings model?", "The amount saved each week", ["The total after 10 weeks", "The chart title", "The formula =B2*B3"]],
  ["Which is an OUTPUT in a pocket-money savings model?", "The total saved after 10 weeks", ["The weekly amount typed in", "The number of weeks typed in", "The heading"]],
  ["Why use cell references (like B2) in formulas instead of typing the number?", "So results update when the value in the cell changes", ["Numbers are not allowed in formulas", "To make it harder to read", "It is the same either way"]],
  ["Which helps users understand a spreadsheet model?", "Clear labels and headings", ["Hiding all labels", "Using random colours", "Putting all data in one cell"]],
  ["A model of a café works out profit. Which formula is best for profit in D2 (income B2, costs C2)?", "=B2-C2", ["=B2+C2", "=C2-B2", "=B2*C2"]],
  ["How can you test your spreadsheet model?", "Enter values where you already know the correct answer and check the result", ["Never change the inputs", "Only look at the colours", "Delete the formulas"]],
  ["What is validation in a spreadsheet?", "A rule that stops wrong data being entered, e.g. only numbers 0–100", ["Printing the spreadsheet", "Making a chart", "Sorting data"]],
  ["Which chart best shows how savings grow week by week?", "A line graph", ["A pie chart", "No chart", "A table of names"]],
  ["A model shows 'Over budget!' when the total is more than the budget. Which function is needed?", "IF", ["MIN", "COUNT", "MAX"]]
],

"9MD.04": [
  ["What does 'evaluate the suitability' of a spreadsheet mean?", "Judge whether it is good enough for the job it needs to do", ["Count its cells", "Change its colours", "Delete it"]],
  ["A spreadsheet has totals typed in as numbers instead of formulas. What is the problem?", "The totals won't update if the data changes", ["It will run faster", "Nothing — it's better", "It uses less memory so it's best"]],
  ["Which feature makes a spreadsheet MORE suitable for young students to use?", "Clear instructions, labels and simple layout", ["Hidden headings", "Tiny text", "No labels at all"]],
  ["A sports club spreadsheet has no column for phone numbers, but the coach needs to call players. It is…", "not suitable for that purpose", ["perfectly suitable", "too suitable", "a database"]],
  ["Which question helps you evaluate an existing spreadsheet?", "Are the formulas correct and do they cover all the data?", ["Who owns the computer?", "How old is the printer?", "What is the file's colour?"]],
  ["A formula =SUM(B2:B9) should add B2 to B10. What is wrong?", "It misses B10, so the total is wrong", ["Nothing is wrong", "It adds too many cells", "SUM can't add"]],
  ["Why is validation a sign of a well-designed spreadsheet?", "It reduces mistakes from wrong data being entered", ["It makes it look nicer", "It hides formulas", "It deletes data"]],
  ["A spreadsheet for 500 students only has rows for 300. It is…", "not suitable — it needs to be expanded", ["suitable", "too big", "a model of the weather"]],
  ["Which would make a spreadsheet LESS suitable?", "Errors in formulas", ["Clear headings", "Charts that summarise data", "Validation rules"]],
  ["A teacher wants to see at a glance who passed. Which feature would help most?", "An IF formula or colour highlighting showing Pass/Fail", ["A blank sheet", "Removing all names", "Smaller font"]],
  ["When evaluating a spreadsheet, you should consider…", "the purpose, the user, accuracy and ease of use", ["only the colour", "only the file name", "only how long it took to make"]],
  ["A budget spreadsheet's numbers are correct but the labels are confusing. What is the best evaluation?", "Accurate, but needs clearer labels to be easy to use", ["Perfect — no changes needed", "Totally useless", "It should be a database"]]
],

"9MD.05": [
  ["What is a relational database?", "A database with two or more tables linked together", ["A single table of data", "A spreadsheet with charts", "A list of family members"]],
  ["What is a record?", "One row in a table — all the data about one item", ["One column in a table", "The whole database", "A search"], {t: ["record"]}],
  ["What is a field?", "One column in a table — one piece of data about each item", ["One row", "The whole table", "A password"], {t: ["field"]}],
  ["What is a primary key?", "A field with a unique value for every record", ["The first field in any table", "A password for the database", "A field that can repeat"]],
  ["What is a foreign key?", "A primary key from one table used in another table to link them", ["A key from another country", "A field that is always empty", "The password to the database"]],
  ["Which field is the best primary key for a Students table?", "StudentID", ["FirstName", "Age", "Class"]],
  ["Why is FirstName a poor primary key?", "Two students could have the same first name", ["Names are too long", "Names are text", "Names never change"]],
  ["Students table has ClassID; Classes table has ClassID as its primary key. In the Students table, ClassID is a…", "foreign key", ["primary key", "record", "query"], {t: ["foreign key"]}],
  ["What is one advantage of linking tables?", "Data is stored once, reducing repeated data (redundancy) and errors", ["Every table must have the same data", "It makes the database slower", "It removes the need for keys"]],
  ["Storing the teacher's name in every student's record is an example of…", "data redundancy (repeated data)", ["a primary key", "a relationship", "validation"]],
  ["A link between two tables is called a…", "relationship", ["record", "field", "formula"], {t: ["relationship"]}],
  ["A Books table and a Loans table are linked by BookID. In which table is BookID the primary key?", "Books", ["Loans", "Both", "Neither"]]
],

"9MD.06": [
  ["What is a query?", "A search that finds records matching certain criteria", ["A table", "A field", "A record"], {t: ["query"]}],
  ["Which search gives FEWER results?", "Year = 8 AND Score > 70", ["Year = 8 OR Score > 70", "Year = 8", "Score > 70"]],
  ["Which search gives MORE results?", "Club = \"Chess\" OR Club = \"Robotics\"", ["Club = \"Chess\" AND Club = \"Robotics\"", "Club = \"Chess\"", "Club = \"Robotics\" AND Year = 8"]],
  ["What does AND mean in a search?", "Both criteria must be true", ["Either criterion can be true", "Neither criterion is true", "Ignore the criteria"]],
  ["What does OR mean in a search?", "At least one of the criteria must be true", ["Both must be true", "Neither must be true", "Only the first is checked"]],
  ["Which criteria find students in Year 8 who scored at least 50?", "Year = 8 AND Score >= 50", ["Year = 8 OR Score >= 50", "Year = 8 AND Score > 50", "Year >= 8 OR Score = 50"]],
  ["What does >= mean?", "Greater than or equal to", ["Less than", "Not equal to", "Greater than only"]],
  ["Which search finds all students NOT in class 8B?", "Class <> \"8B\"", ["Class = \"8B\"", "Class > \"8B\"", "Class AND \"8B\""]],
  ["Why can Club = \"Chess\" AND Club = \"Art\" return no results (if each student has one club)?", "One field can't hold two different values at the same time", ["AND never works", "The database is broken", "There are too many records"]],
  ["Find books by 'Rowling' published after 2000. Which criteria?", "Author = \"Rowling\" AND Year > 2000", ["Author = \"Rowling\" OR Year > 2000", "Author > 2000", "Year = \"Rowling\""]],
  ["A 'complex search' uses…", "two or more criteria", ["exactly one criterion", "no criteria", "only numbers"]],
  ["Find students aged 12 to 14. Which criteria?", "Age >= 12 AND Age <= 14", ["Age >= 12 OR Age <= 14", "Age = 12 AND Age = 14", "Age > 12 AND Age < 14"]]
],

"9MD.07": [
  ["Why search across linked tables in a relational database?", "To combine related data, e.g. student names with their teacher's name", ["To delete tables", "Because single tables can't be searched", "To create primary keys"]],
  ["Students(StudentID, Name, ClassID) and Classes(ClassID, Teacher). To find names of Ms Lim's students, which field links the tables?", "ClassID", ["Name", "Teacher", "StudentID"]],
  ["Which search finds Ms Lim's students who scored over 70?", "Teacher = \"Ms Lim\" AND Score > 70", ["Teacher = \"Ms Lim\" OR Score > 70", "Score = \"Ms Lim\"", "Teacher > 70"]],
  ["In a library database, Members and Loans are linked by MemberID. Which question needs BOTH tables?", "Which members have books that are overdue?", ["How many members are there?", "What is member M01's phone number?", "What is the library's name?"]],
  ["What must exist for two tables to be searched together?", "A relationship using a primary key and foreign key", ["The same number of records", "Identical field names everywhere", "A chart"]],
  ["Orders(OrderID, CustomerID, Total) and Customers(CustomerID, City). Find orders over $50 from Hanoi customers:", "City = \"Hanoi\" AND Total > 50", ["City = \"Hanoi\" OR Total > 50", "Total = \"Hanoi\"", "CustomerID > 50"]],
  ["Which result shows the search was created correctly?", "Every record returned matches all the criteria", ["It returns every record", "It returns no fields", "It changes the data"]],
  ["Why should you test a query?", "To check it returns exactly the right records — no more, no less", ["Queries never have mistakes", "To make the database bigger", "To add new tables"]],
  ["Search: Club = \"Chess\" OR Club = \"Robotics\" AND Year = 8. Why add brackets: (Club = \"Chess\" OR Club = \"Robotics\") AND Year = 8?", "To make sure Year = 8 applies to both clubs", ["Brackets are decoration", "To make it slower", "Brackets delete records"]],
  ["Which field would you show in the results to identify students by name?", "Name", ["ClassID only", "Primary key only", "No fields"]],
  ["In a query, criteria are…", "the conditions records must meet", ["the table names", "the colours of the fields", "the database password"]],
  ["Patients and Appointments are linked by PatientID. To list patients with an appointment on Monday, you search…", "Appointments.Day = \"Monday\" and show Patients.Name", ["Patients.Name = \"Monday\"", "PatientID = \"Monday\"", "Only the Patients table"]]
],

"9MD.08": [
  ["What is Big Data?", "Data sets so large, fast-growing and varied that normal software can't process them", ["Any file bigger than 1 MB", "A very big spreadsheet printed on paper", "A database with two tables"]],
  ["What does 'Volume' mean in Big Data?", "The huge amount of data", ["How fast data arrives", "The different types of data", "How loud the data is"], {t: ["amount", "size"]}],
  ["What does 'Velocity' mean in Big Data?", "The speed at which data is created and collected", ["The amount of data", "The variety of data", "The accuracy of data"], {t: ["speed"]}],
  ["What does 'Variety' mean in Big Data?", "The many different types of data, e.g. text, images, video, GPS", ["The speed of data", "The amount of data", "The cost of data"]],
  ["What are the 3 Vs of Big Data?", "Volume, velocity, variety", ["Value, vision, voice", "Video, voice, volume", "Virus, version, velocity"]],
  ["What does 'Veracity' mean?", "How accurate and trustworthy the data is", ["How fast data travels", "How big the data is", "How old the data is"]],
  ["Which is a source of Big Data?", "Social media posts", ["A single shopping list", "A handwritten diary", "A calculator"]],
  ["How do online shops use Big Data?", "To recommend products based on what customers browse and buy", ["To print receipts", "To stop all sales", "To slow down websites"]],
  ["How do map apps use Big Data?", "Live location data from many phones shows traffic jams", ["They guess randomly", "They only use paper maps", "They ask each driver by phone"]],
  ["How can Big Data help healthcare?", "Spotting patterns, like early signs of a disease outbreak", ["Replacing all doctors", "Making medicine free", "Deleting patient records"]],
  ["Which is a CONCERN about Big Data?", "Privacy — people may not know how their data is used", ["It is too small", "It is always accurate", "It is never stored"]],
  ["Why can't Big Data be analysed with a normal spreadsheet?", "There is too much data, arriving too fast, in too many forms", ["Spreadsheets only work with words", "Big Data is secret", "Spreadsheets are too new"]],
  ["Sensors on machines, smart watches and smart meters that send data are part of…", "the Internet of Things", ["a bus topology", "a compiler", "a trace table"]],
  ["How do weather services use Big Data?", "Combining huge amounts of satellite and sensor data to improve forecasts", ["Looking out of the window only", "Asking one person", "Printing old forecasts"]],
  ["How do sports teams use Big Data?", "Analysing player movement and performance to improve tactics", ["Choosing kit colours randomly", "Selling tickets on paper", "Stopping training"]],
  ["Which technology is often used to find patterns in Big Data?", "Machine learning", ["Defragmentation", "Parity bits", "Bus networks"]],
  ["How does Big Data help banks?", "Spotting unusual transactions quickly to detect fraud", ["Making all loans free", "Printing more money", "Closing all branches"]],
  ["A 'smart city' uses Big Data to…", "manage things like traffic lights, energy and public transport", ["stop people using phones", "remove all roads", "close the internet"]],
  ["Which is an example of Velocity?", "Thousands of tweets posted every second", ["A large hard drive", "A photo and a video", "One email a week"]],
  ["Which is an example of Variety?", "A company collecting videos, reviews, clicks and GPS data", ["Storing 10 TB of numbers", "Data arriving every second", "Only collecting names"]],
  ["What is a security risk of Big Data?", "A data breach could expose millions of people's information", ["It makes passwords stronger", "It stops hackers", "It is always encrypted"]],
  ["What does 'Value' mean in Big Data?", "How useful the data is for making decisions", ["The price of a hard drive", "The speed of data", "The number of files"]],
  ["Which is the BEST definition of Big Data applications?", "Ways organisations use huge data sets to find patterns and make better decisions", ["Apps that are large in size", "Programs that delete data", "Games with large maps"]]
],

"9DC.01": [
  ["What is a network topology?", "The layout of how devices on a network are connected", ["A type of cable", "A network password", "A computer virus"], {t: ["layout"]}],
  ["In which topology are all devices connected to ONE main cable?", "Bus", ["Star", "Ring", "Mesh"], {t: ["bus"]}],
  ["In which topology is each device connected to a central switch?", "Star", ["Bus", "Ring", "Line"], {t: ["star"]}],
  ["In which topology is each device connected to two others, forming a circle?", "Ring", ["Bus", "Star", "Tree"], {t: ["ring"]}],
  ["What happens in a BUS network if the main cable breaks?", "The whole network fails", ["Only one device is affected", "Nothing happens", "The network gets faster"]],
  ["What happens in a STAR network if one device's cable breaks?", "Only that device loses connection", ["The whole network fails", "All devices restart", "Data goes round the ring"]],
  ["What happens in a STAR network if the central switch fails?", "The whole network fails", ["Only one device fails", "Nothing happens", "Data uses the backbone instead"]],
  ["Which topology usually uses the LEAST cable?", "Bus", ["Star", "Ring", "They all use the same"]],
  ["Which topology needs the MOST cable?", "Star", ["Bus", "Ring", "None — they are wireless"]],
  ["In a ring network, data travels…", "around the ring in one direction", ["only to the central switch", "along a single backbone", "randomly"]],
  ["Which topology is most common in schools and offices?", "Star", ["Bus", "Ring", "None"]],
  ["Why can a bus network slow down with lots of devices?", "Data collisions on the single shared cable", ["The switch is too fast", "Rings are too small", "There is no cable"]],
  ["What is the main cable in a bus network called?", "The backbone", ["The switch", "The router", "The ring"], {t: ["backbone"]}],
  ["What is a disadvantage of a ring topology?", "If one device or cable fails, the whole ring can stop", ["It uses the most cable", "Data always collides", "It needs a central switch"]],
  ["What is a node?", "Any device connected to a network", ["A type of cable", "A network error", "A password"], {t: ["node"]}],
  ["What does a switch do in a star network?", "Receives data and sends it only to the device it is meant for", ["Turns the network off", "Connects to the bus backbone", "Stores all the files"]],
  ["What is the difference between a LAN and a WAN?", "A LAN covers a small area; a WAN covers a large area", ["A LAN is wireless; a WAN is wired", "They are the same", "A WAN is smaller"]],
  ["Which device connects a home network to the internet?", "Router", ["Switch", "Mouse", "Monitor"], {t: ["router"]}],
  ["What is an advantage of a ring topology?", "No data collisions, since data flows in one direction", ["If one device fails nothing happens", "It uses no cable", "Easiest to add devices"]],
  ["In a client–server network, what does the server do?", "Stores files and manages logins, security and backups for the clients", ["Only prints documents", "Plays games", "Nothing"]],
  ["What is a peer-to-peer network?", "All computers are equal and share directly, without a server", ["A network with one main server", "A network with no computers", "A network made of printers"]],
  ["Which is an advantage of a star topology?", "Faults are easy to find and new devices are easy to add", ["It needs the least cable", "It has no central device", "It is the cheapest"]],
  ["What is at the ends of a bus cable to stop signals bouncing back?", "Terminators", ["Switches", "Routers", "Servers"]],
  ["Which topology has a 'single point of failure' at the centre?", "Star", ["Bus", "Ring", "Peer-to-peer"]]
],

"9DC.02": [
  ["What is a protocol?", "A set of rules for how devices communicate and send data", ["A type of cable", "A computer virus", "A network diagram"]],
  ["Why do networks need protocols?", "So devices from different makers can understand each other", ["To make cables longer", "To slow down data", "To stop all communication"]],
  ["What does TCP do?", "Splits data into packets, numbers them and reassembles them in order", ["Gives web pages colour", "Encrypts passwords only", "Powers the router"]],
  ["What does IP do?", "Gives devices addresses and routes packets to the correct one", ["Reassembles packets", "Displays web pages", "Prints documents"]],
  ["What does HTTP do?", "Sets the rules for requesting and sending web pages", ["Sends emails", "Gives IP addresses", "Defragments disks"]],
  ["What is the difference between HTTP and HTTPS?", "HTTPS encrypts the data so it is secure", ["HTTPS is slower and less secure", "There is no difference", "HTTP is newer"]],
  ["What is a packet?", "A small piece of data sent across a network", ["A whole file", "A network cable", "A type of router"], {t: ["packet"]}],
  ["What does a packet header contain?", "Information such as the sender's and receiver's IP addresses and the packet number", ["The whole message", "The user's password", "A picture"]],
  ["What does TCP do if a packet goes missing?", "Asks for it to be sent again", ["Ignores it", "Deletes all packets", "Turns off the computer"]],
  ["Why are packets numbered?", "So they can be put back in the right order", ["To make them heavier", "To count how many users there are", "To encrypt them"]],
  ["Which is an example of an IP address?", "192.168.1.5", ["www.school.edu", "HTTP", "abc@mail.com"]],
  ["Do all packets of the same message have to take the same route?", "No — they can take different routes and are reassembled at the end", ["Yes, always", "Only on Mondays", "Packets don't travel"]],
  ["Which protocol would be used when you open a website?", "HTTP or HTTPS", ["FTP only", "SMTP", "Parity"]],
  ["You should check for HTTPS (the padlock) before…", "entering passwords or payment details", ["reading the news", "looking at pictures", "closing the browser"]],
  ["What does TCP stand for?", "Transmission Control Protocol", ["Total Computer Power", "Text Copy Protocol", "Transfer Cable Port"]],
  ["What does HTTP stand for?", "Hypertext Transfer Protocol", ["High Tech Transfer Program", "Home Text Typing Protocol", "Hyperlink Total Transfer Protocol"]],
  ["What does IP stand for?", "Internet Protocol", ["Internal Program", "Input Port", "Information Packet"]],
  ["Which protocol is used to send email?", "SMTP", ["HTTP", "TCP", "FTP"]],
  ["Which protocol is used to transfer files between computers?", "FTP", ["SMTP", "HTTP", "IMAP"]],
  ["The actual data carried in a packet is called the…", "payload", ["header", "address", "protocol"], {t: ["payload"]}],
  ["Which pair work together to send data across the internet?", "TCP and IP", ["HTTP and Word", "Bus and ring", "RAM and ROM"]],
  ["In HTTP, the web browser is the ______ and the website's computer is the ______.", "client, server", ["server, client", "router, switch", "packet, header"]]
],

"9DC.03": [
  ["What does 'scalable' mean for a network?", "It can grow easily (more users/devices) without being rebuilt", ["It can be weighed", "It can only have 5 devices", "It is very cheap"]],
  ["Which topology is the MOST scalable?", "Star — just plug new devices into the switch", ["Bus — more devices make it faster", "Ring — adding a device is easy", "None of them"]],
  ["Why is a bus network not very scalable?", "It slows down with more devices because of data collisions", ["It has too many switches", "It cannot connect computers", "It is wireless only"]],
  ["What is bandwidth?", "The amount of data that can be sent per second", ["The length of a cable", "The number of users", "The size of a monitor"], {t: ["bandwidth"]}],
  ["A school adds 200 tablets that stream video. Which factor is MOST important?", "Bandwidth", ["Font size", "Screen colour", "Keyboard type"]],
  ["Why should a network designer buy switches with spare ports?", "So new devices can be added later", ["To make the network slower", "Ports are decoration", "To reduce security"]],
  ["Which is a scalability factor to consider?", "Expected growth in the number of users", ["The colour of cables", "The teacher's name", "The day of the week"]],
  ["Why can Wi-Fi help scalability?", "New devices can join without running new cables", ["Wi-Fi is always faster than cable", "Wi-Fi needs no security", "Wi-Fi uses no bandwidth"]],
  ["How can cloud services help a network scale?", "Extra storage or servers can be added quickly when needed", ["They stop growth", "They need new buildings", "They remove the internet"]],
  ["Why is cost a scalability factor?", "Upgrades and extra hardware for growth must fit the budget", ["Networks are free", "Cost only matters for printers", "Cost never changes"]],
  ["Why does security become harder as a network grows?", "More devices and users mean more ways for attackers to get in", ["Bigger networks are always safer", "Hackers ignore big networks", "It doesn't change"]],
  ["Why is a ring network hard to scale?", "Adding a device means breaking the ring, disrupting the network", ["Rings can't have more than 2 devices", "It uses a central switch", "Rings are wireless"]]
],

"9DC.04": [
  ["What is a parity bit?", "An extra bit added to data to help detect transmission errors", ["The first bit of every file", "A bit that stores a password", "A broken bit"]],
  ["With EVEN parity, the total number of 1s (including the parity bit) must be…", "even", ["odd", "zero", "eight"], {t: ["even"]}],
  ["With ODD parity, the total number of 1s (including the parity bit) must be…", "odd", ["even", "zero", "seven"], {t: ["odd"]}],
  ["Using even parity, what is the parity bit for data 1011001?", "0", ["1", "4", "2"], {t: true, e: "There are four 1s (already even), so the parity bit is 0."}],
  ["Using even parity, what is the parity bit for data 1110000?", "1", ["0", "3", "4"], {t: true}],
  ["What can cause bits to change during transmission?", "Interference", ["Using even parity", "A strong password", "Too much storage"]],
  ["Even parity is used. A byte arrives with five 1s. What does the receiver conclude?", "An error has occurred", ["The data is correct", "The parity bit is 5", "Odd parity was used"]],
  ["What happens when a parity check finds an error?", "The data is usually sent again", ["The computer shuts down", "The data is accepted anyway", "The parity bit is deleted"]],
  ["What is a limitation of a single parity bit?", "If two bits flip, the error is not detected", ["It detects every possible error", "It always finds which bit is wrong", "It uses no extra data"]],
  ["Can a single parity bit tell you WHICH bit is wrong?", "No — only that an error happened", ["Yes, always", "Only with odd parity", "Only for 8-bit data"]],
  ["What must the sender and receiver agree on before using parity?", "Whether even or odd parity is used", ["The colour of the data", "The user's password", "The file name"]],
  ["What does a 2D parity check add?", "A parity bit for each row AND a parity bit for each column", ["Two passwords", "Two copies of the file", "Only a parity bit for the first row"]],
  ["How does a 2D parity check find the wrong bit?", "It is where the row with bad parity meets the column with bad parity", ["It guesses", "It is always the first bit", "It sends the data twice"]],
  ["What is the main advantage of a 2D parity check?", "It can locate and correct a single-bit error", ["It uses no extra bits", "It works without any parity", "It detects every error ever"]],
  ["In a 2D parity check, the extra row of column parity bits is called the…", "parity byte", ["header", "payload", "backbone"], {t: ["parity byte"]}]
],

"9DC.05": [
  ["Which data needs the STRONGEST security?", "Students' medical records", ["The school lunch menu", "The school's public address", "Sports day photos already on the website"]],
  ["Why might a school NOT use expensive biometric scanners for the lunch menu page?", "The data is public and not sensitive, so the cost isn't justified", ["Biometrics don't work", "Menus are top secret", "Biometrics are free"]],
  ["What does 'accessibility' mean when choosing security?", "Security shouldn't make it too hard for the right people to use the system", ["Anyone should be able to see everything", "No passwords allowed", "Only teachers can log in"]],
  ["What can happen if passwords rules are TOO strict?", "Users write passwords down, making the system less secure", ["The network gets faster", "Hackers give up", "Nothing"]],
  ["What does encryption do?", "Scrambles data so only someone with the key can read it", ["Deletes data", "Makes files bigger", "Speeds up the network"]],
  ["What is two-factor authentication?", "Using two different checks, e.g. a password and a code sent to your phone", ["Using two passwords that are the same", "Logging in twice", "Having two computers"]],
  ["What do access levels (user permissions) do?", "Let users see only the data they need", ["Give everyone full access", "Speed up the network", "Remove passwords"]],
  ["Which is a physical security method?", "A locked server room", ["Anti-malware", "Encryption", "A firewall"]],
  ["Why are backups part of network security?", "Data can be restored if it is lost, deleted or locked by ransomware", ["They stop hackers getting in", "They make passwords stronger", "They speed up the internet"]],
  ["What is phishing?", "Fake emails or messages that trick people into giving away personal details", ["A type of network cable", "Catching fish online", "A parity check"]],
  ["A small charity has a tiny budget. Which security choice is most sensible?", "Free anti-malware, strong passwords and regular backups", ["Hiring 20 security guards", "Biometric scanners on every door", "No security at all"]],
  ["Which factors should be balanced when choosing network security?", "How sensitive the data is, the cost and accessibility", ["Cable colour, font and screen size", "Only the cost", "Only how fast it is"]],
  ["Which security method scrambles data so it can't be read without a key?", "Encryption", ["Backup", "Firewall", "Biometrics"], {t: ["encryption"]}],
  ["Which security method checks network traffic and blocks suspicious connections?", "Firewall", ["Encryption", "Backup", "Phishing"], {t: ["firewall", "a firewall"]}],
  ["Fingerprint and face recognition are examples of which security method?", "Biometrics", ["Encryption", "Phishing", "Backups"], {t: ["biometrics", "biometric"]}],
  ["Fake emails that trick people into giving away passwords are called…", "Phishing", ["Encryption", "Firewalls", "Biometrics"], {t: ["phishing"]}],
  ["How can machine learning help network security?", "By learning normal activity and flagging unusual behaviour such as fraud or new malware", ["By deleting all data", "By making passwords shorter", "By turning off the firewall"]]
]
});
